'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ParallaxProvider } from 'react-scroll-parallax'
import { MouseParallaxContainer, MouseParallaxChild } from "react-parallax-mouse";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ParallaxProvider scrollAxis='vertical'>
      <MouseParallaxContainer globalFactorX={0.1} globalFactorY={0.1}>

        {children}
        </MouseParallaxContainer>
        </ParallaxProvider>
        </body>
    </html>
  )
}
